language: scala
scala:
- 2.11.8
jdk: oraclejdk8
env:
  secure: jeLrIzCmGFhZCQszFu+lKTkhm5kro9wB3zrMiIz7v5cM2eR1GcJaWDC36X0EaIuNZnh7QsLilo1gTe02q0zHVvZvb92eKpcP8Z+c68+mHVtlNohmMvdFIXnUnh0cwyMBWmReTwG0YEK+Zp4HSE0QHRI8Qj9Y8B4z2FLXMn9v8tiuvb5sC1MyWjR5j1ruYjSKvWGOdTsu+5IWyAXd+3Z2n1aBKKkLcI4ys+HuFkQe8RxLL7zaBNt46R9g9E9Vyl/5EPQyDvisxxrvC6ciHdtcfa1IX8ZneK++Tv6hAJaAOwxPl+lv+2lxfMsljS0bVfhwIOx3R6o8jrrFT5nOiKDJfAX0OcpAoRttAlbdzs+K49764JhkJUM03rlcmfWMC0CqPNkD1Ek0V+WWoHi65ikuhLdPf0vNTcIA4umgCL7apdFzvJerzG1k9P6+L+BPMn+ycYiEXe3ms2mBUe1jE1Apvc+Re2/DKOrdQxTuhsoyrSdV7oS2CoeDJo87IetidWtPlNkVH/StnFXfYrjav8p8Cm3YzBK2J9f4oPk65XA+efx4Wc3zLJ7SUSLAv9W3LaAB0Q4uOhcOACirODmgmLUBxl3NmMqKq7Z9JSFwh6y8KVirzeeA83EwgK4QifeBQXnvm53K0cVEU5rFDVBuNU2fTeXC6sRM7hC2h/fw1EQLT+0=

script: sbt test it:test
