sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.2
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
script: sbt ++$TRAVIS_SCALA_VERSION test it:test
env:
  secure: fgCX9/AQpXyQysSpd20dNLFmdzqNr+jEj195D3D5MMT4dC3oH6y2ksY/QJJqEpjAcG5JPgJmg5aAkUxvXMsxcom7xOatGSD/0iE4sAJNwyoLRP5HB/m35F2EgDQgS8Fs++AARgHIKdg19cKkaCfSA32l6iHg+TyMYfxGrFoT6dOKUIqhhPbJLzYT2C1Z3JqO3Zd/eWNxToJa9N8wamrTO8tQJuAtcPrLrfJBy9P+jy++0EkyhMRMPHCk9hY4IS8GeOR4momSWMADxdmPUbHlFVncDOK1B1e7HxPaHJgYLCXBNBk1FWhE9PyY61iBqMZ/LKlEf3lTRx0GbPWXX2SzxNkFLkvHpFYDT5D9OMeNChMQLE/zyv8eQanTF4Bjv7W3ELGDWB3GzcWfTdNcc2HOC39f8nGZVVFTedQF0j6/mJ67OPMf93EQa5k/0qmRCfu0WXTRzItmjEYQn/Km7Y/8vaclbuW1s/bh6l+SO2Z8Yv2XTTyBe18HxoePO/fRg/XvSAJGzepNCBGbJrXM/N6UWyNVxdZcfvXgGVMaivxtMCb0EM/rJ+Q+20N3V1H6wNo/yu3ygKHjEhmLweldyRygqBq9YZFNzILUATCz9cMbheOCowNLLKA23hbaMLg0PWic2o+kkBsVtyhpoGz7CFWa/H7UBJd2RC8Iqb4Hgy2N70M=
